Vagrant.configure("2") do |config|

  config.ssh.insert_key = false 

  config.vm.box = "debian/bullseye64" #15

  config.vm.network "forwarded_port", guest: 5000, host: 5000 #26

  config.vm.synced_folder "./app/", "/app", type: "virtualbox" #46
  
  config.vm.provision "shell", path: 'provision.sh'

end
