apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    service: load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    service: flask