version: "3.1"
services:
  db:
    container_name: con_db
    image: arangodb:latest
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=passwd
      
  web:
    container_name: con_web
    image: anderra57/arango-uni:latest
    restart: always
    depends_on: 
      - db
    ports:
      - 5000:5000
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - ARANGO_NAME=con_db
      - ARANGO_PASS=passwd
      - WEB_ADMIN=ulopeznovoa
      - WEB_PASS=1234
    command: python /app/app.py